spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:take_it_bot}

  jpa:
    open-in-view: false

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}

file:
  upload-dir: ${FILE_UPLOAD_DIR:/app/uploads}

logging:
  file:
    name: ${APP_LOG_FILE:/app/logs/app.log}

