CREATE TYPE order_status AS ENUM ('pending', 'confirmed', 'preparing', 'ready', 'completed', 'cancelled');

--Таблица пользователи
CREATE TABLE users (
                       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(100) UNIQUE NOT NULL,
                       telegram_id TEXT UNIQUE,
                       chat_id BIGINT,
                       is_active BOOLEAN DEFAULT true,
                       is_admin BOOLEAN DEFAULT false,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Таблица категорий
CREATE TABLE category (
                          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name TEXT NOT NULL,
                          description TEXT,
                          parent_id INTEGER REFERENCES category(id) ON DELETE SET NULL,
                          is_active BOOLEAN DEFAULT true,
                          sort_order INTEGER DEFAULT 0
);

-- 1. Создаем таблицу типов добавок (если хотим группировать их)
CREATE TABLE addon_type (
                            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(100) NOT NULL UNIQUE, -- "Сиропы", "Альтернативное молоко"
                            description TEXT,
                            sort_order INTEGER DEFAULT 0,
                            is_active BOOLEAN DEFAULT true
);
-- Таблица дополнительных опций для продуктов
CREATE TABLE product_addon (
                               id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               product_id INTEGER NOT NULL REFERENCES product(id) ON DELETE CASCADE,
                               addon_product_id INTEGER NOT NULL REFERENCES product(id) ON DELETE CASCADE,
                               additional_price INTEGER DEFAULT 0,
                               is_required BOOLEAN DEFAULT false,
                               max_quantity INTEGER DEFAULT 1, -- максимальное количество этой добавки
                               is_active BOOLEAN DEFAULT true,
                               sort_order INTEGER DEFAULT 0,
                               created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                               UNIQUE(product_id, addon_product_id) -- одна добавка к продукту только раз
);

-- Таблица продуктов
CREATE TABLE product (
                         id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name TEXT NOT NULL,
                         amount INTEGER NOT NULL,
                         size VARCHAR,
                         count INTEGER DEFAULT 0,
                         available BOOLEAN DEFAULT true,
                         photo TEXT,
                         description TEXT,
                         category_id INTEGER NOT NULL REFERENCES category(id) ON DELETE RESTRICT
);

-- Таблица корзин (shopping carts)
CREATE TABLE cart (
                      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Таблица элементов корзины (cart items)
CREATE TABLE cart_item (
                           id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           cart_id INTEGER NOT NULL REFERENCES cart(id) ON DELETE CASCADE,
                           product_id INTEGER NOT NULL REFERENCES product(id) ON DELETE CASCADE,
                           count_product INTEGER DEFAULT 1,
                           special_instructions TEXT,
                           added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cart_item_addon (
                                 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 cart_item_id INTEGER NOT NULL REFERENCES cart_item(id) ON DELETE CASCADE,
                                 addon_product_id INTEGER NOT NULL REFERENCES product(id) ON DELETE CASCADE,
                                 quantity INTEGER DEFAULT 1,
                                 price_at_selection INTEGER NOT NULL, -- цена на момент выбора
                                 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                 UNIQUE(cart_item_id, addon_product_id) -- уникальная комбинация
);

-- Таблица заказов (orders) - отсутствует на схеме, но явно нужна
CREATE TABLE orders (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
                        total_amount INTEGER,
                        status order_status DEFAULT 'pending',
                        date_order TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Таблица элементов заказа (order items)
CREATE TABLE order_item (
                            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            product_id INTEGER NOT NULL REFERENCES product(id) ON DELETE RESTRICT,
                            count_product INTEGER DEFAULT 1,
                            price_at_time INTEGER NOT NULL,
                            product_name TEXT NOT NULL,
                            order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE
);

-- 1. Создаем таблицу для хранения добавок в заказах
CREATE TABLE order_item_addon (
                                  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  order_item_id INTEGER NOT NULL REFERENCES order_item(id) ON DELETE CASCADE,
                                  addon_product_id INTEGER REFERENCES product(id) ON DELETE SET NULL,
                                  quantity INTEGER DEFAULT 1,
                                  price_at_order INTEGER NOT NULL, -- цена на момент заказа
                                  addon_product_name TEXT, -- название на момент заказа (на случай если продукт удалят)
                                  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Индексы для улучшения производительности
CREATE INDEX idx_cart_user_id ON cart(user_id);
CREATE INDEX idx_cart_item_cart_id ON cart_item(cart_id);
CREATE INDEX idx_cart_item_product_id ON cart_item(product_id);
CREATE INDEX idx_order_item_product_id ON order_item(product_id);
CREATE INDEX idx_order_item_order_id ON order_item(order_id);
CREATE INDEX idx_product_category_id ON product(category_id);
CREATE INDEX idx_category_parent_id ON category(parent_id);
CREATE INDEX idx_orders_user_id ON orders(user_id);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_product_addon_product_id ON product_addon(product_id);
CREATE INDEX idx_product_addon_addon_product_id ON product_addon(addon_product_id);
CREATE INDEX idx_order_item_addon_order_item_id ON order_item_addon(order_item_id);
CREATE INDEX idx_order_item_addon_addon_product_id ON order_item_addon(addon_product_id);
CREATE INDEX idx_cart_item_addon_cart_item_id ON cart_item_addon(cart_item_id);
CREATE INDEX idx_cart_item_addon_addon_product_id ON cart_item_addon(addon_product_id);

-- Триггер для автоматического обновления updated_at в таблице card
CREATE OR REPLACE FUNCTION update_updated_at_column()
    RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_cart_updated_at
    BEFORE UPDATE ON cart
    FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- Триггер для обновления updated_at в таблице orders
CREATE TRIGGER update_orders_updated_at
    BEFORE UPDATE ON orders
    FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- Функция для расчета общей суммы корзины
CREATE OR REPLACE FUNCTION calculate_cart_total(cart_id_param INTEGER)
    RETURNS INTEGER AS $$
DECLARE
    total INTEGER;
BEGIN
    SELECT COALESCE(SUM(p.amount * ci.count_product), 0)
    INTO total
    FROM cart_item ci
             JOIN product p ON ci.product_id = p.id
    WHERE ci.cart_id = cart_id_param;

    RETURN total;
END;
$$ LANGUAGE plpgsql;

-- Функция для проверки доступности продукта
CREATE OR REPLACE FUNCTION check_product_availability()
    RETURNS TRIGGER AS $$
BEGIN
    IF (SELECT count FROM product WHERE id = NEW.product_id) < NEW.count_product THEN
        RAISE EXCEPTION 'Недостаточно товара на складе';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER check_cart_item_availability
    BEFORE INSERT OR UPDATE ON cart_item
    FOR EACH ROW
EXECUTE FUNCTION check_product_availability();